# Generated by Django 5.2 on 2025-04-29 18:08

import common.image_utils
import common.unique_file_path_generators
import common.validators
import django.core.validators
import django.db.models.deletion
import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_set_wallpapers_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(
                    r'^(?!.*\s{2,})[a-z]+(?: [a-z]+)*$',
                    'Ensure that the name contains only lowercase English letters or spaces, with no leading or trailing spaces and no consecutive spaces.'
                )])),
                ('thumbnail', models.ImageField(max_length=256, null=True, upload_to=common.unique_file_path_generators.UniqueFilePathGenerator(pathlib.PurePosixPath('category-thumbnails'), 'image'), validators=[common.validators.MaxFileSizeValidator(1048576), common.validators.ImageFormatAndFileExtensionsValidator((common.image_utils.ImageFormat['JPEG'], common.image_utils.ImageFormat['PNG'], common.image_utils.ImageFormat['WEBP'])), common.validators.ImageDimensionValidator(min_height=512, min_width=512)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(max_length=256, unique=True, upload_to=common.unique_file_path_generators.UniqueFilePathGenerator(pathlib.PurePosixPath('wallpapers'), 'image'), validators=[common.validators.MaxFileSizeValidator(7340032), common.validators.ImageFormatAndFileExtensionsValidator((common.image_utils.ImageFormat['JPEG'],)), common.validators.ImageDimensionValidator(min_height=1024, min_width=1024)]),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallpapers', to='app.category'),
        ),
    ]
