# Generated by Django 5.2 on 2025-04-29 19:03

from pathlib import Path
from django.conf import settings
from django.db import migrations
from common.data_migration_utils import DeleteHistoricalModelData
from common.image_utils import get_file_extensions_for_image_format, ImageFormat
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.core.files.images import ImageFile
from django.db.models.query import QuerySet
from typing import Any



wallpapers_directory: Path = settings.BASE_DIR / 'images/wallpapers/'
categories_directory: Path = settings.BASE_DIR / 'images/categories/'
delete_category_data = DeleteHistoricalModelData('app', 'Category', ('thumbnail', ))


def set_categories_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Category = apps.get_model('app', 'Category')
    Wallpaper = apps.get_model('app', 'Wallpaper')

    jpeg_extensions = get_file_extensions_for_image_format(ImageFormat.JPEG)
    wallpapers: QuerySet[Any] = Wallpaper.objects.all()

    abstract_wallpapers = wallpapers[0:5]
    animal_wallpapers = wallpapers[5:10]
    couple_wallpapers = wallpapers[10:13]
    nails_wallpapers = wallpapers[13:17]
    paradise_wallpapers = wallpapers[17:22]
    space_wallpapers = wallpapers[22:26]
    train_wallpapers = wallpapers[26:31]

    with Path((categories_directory / 'abstract.webp').relative_to(settings.BASE_DIR)).open('rb') as abstract_thumbnail, \
        Path((categories_directory / 'couple.webp').relative_to(settings.BASE_DIR)).open('rb') as couple_thumbnail, \
        Path((categories_directory / 'paradise.webp').relative_to(settings.BASE_DIR)).open('rb') as paradise_thumbnail, \
        Path((categories_directory / 'space.jpg').relative_to(settings.BASE_DIR)).open('rb') as space_thumbnail, \
        Path((categories_directory / 'train.webp').relative_to(settings.BASE_DIR)).open('rb') as train_thumbnail:

        abstract_category = Category.objects.create(name='abstract', thumbnail=ImageFile(abstract_thumbnail))
        for wp in abstract_wallpapers:
            wp.category = abstract_category
        Wallpaper.objects.bulk_update(abstract_wallpapers, ['category'])

        couple_category = Category.objects.create(name='couple', thumbnail=ImageFile(couple_thumbnail))
        for wp in couple_wallpapers:
            wp.category = couple_category
        Wallpaper.objects.bulk_update(couple_wallpapers, ['category'])

        paradise_category = Category.objects.create(name='paradise', thumbnail=ImageFile(paradise_thumbnail))
        for wp in paradise_wallpapers:
            wp.category = paradise_category
        Wallpaper.objects.bulk_update(paradise_wallpapers, ['category'])

        space_category = Category.objects.create(name='space', thumbnail=ImageFile(space_thumbnail))
        for wp in space_wallpapers:
            wp.category = space_category
        Wallpaper.objects.bulk_update(space_wallpapers, ['category'])

        train_category = Category.objects.create(name='train', thumbnail=ImageFile(train_thumbnail))
        for wp in train_wallpapers:
            wp.category = train_category
        Wallpaper.objects.bulk_update(train_wallpapers, ['category'])

    animal_category = Category.objects.create(name='animal')
    for wp in animal_wallpapers:
        wp.category = animal_category
    Wallpaper.objects.bulk_update(animal_wallpapers, ['category'])

    nails_category = Category.objects.create(name='nails')
    for wp in nails_wallpapers:
        wp.category = nails_category
    Wallpaper.objects.bulk_update(nails_wallpapers, ['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_alter_wallpaper_image_wallpaper_category'),
    ]

    operations = [
        migrations.RunPython(
            set_categories_data,
            delete_category_data
        )
    ]
