# Generated by Django 5.2 on 2025-05-01 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_set_categories_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to='app.category'),
        ),
    ]
