# Generated by Django 5.2 on 2025-05-03 10:31

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils.text import slugify


def set_category_slugs(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Category = apps.get_model('app', 'Category')

    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()


def delete_category_slugs(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Category = apps.get_model('app', 'Category')

    for category in Category.objects.all():
        category.slug = None
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_slug'),
    ]

    operations = [
        migrations.RunPython(
            set_category_slugs,
            delete_category_slugs
        )
    ]
