# Generated by Django 5.2 on 2025-05-05 10:32

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def set_wallpaper_slugs(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Wallpaper = apps.get_model('app', 'Wallpaper')

    for wallpaper in Wallpaper.objects.all():
        wallpaper.slug = wallpaper.uuid.hex
        wallpaper.save()


def delete_wallpaper_slugs(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Wallpaper = apps.get_model('app', 'Wallpaper')

    for wallpaper in Wallpaper.objects.all():
        wallpaper.slug = None
        wallpaper.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wallpaper_slug'),
    ]

    operations = [
        migrations.RunPython(
            set_wallpaper_slugs,
            delete_wallpaper_slugs
        )
    ]
