# Generated by Django 5.2 on 2025-05-05 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_set_wallpaper_slug_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='slug',
            field=models.SlugField(max_length=32, validators=[django.core.validators.MinLengthValidator(32), django.core.validators.RegexValidator('^[0-9a-f]$', "Ensure that the UUID contains only digits and the lowercase English letters 'a' to 'f'.")]),
        ),
    ]
