# Generated by Django 5.2 on 2025-05-19 03:51

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def set_wallpaper_width_height(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Wallpaper = apps.get_model('app', 'Wallpaper')

    for wallpaper in Wallpaper.objects.all():
        wallpaper.image = wallpaper.image
        wallpaper.save()


def delete_wallpaper_width_height(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Wallpaper = apps.get_model('app', 'Wallpaper')

    for wallpaper in Wallpaper.objects.all():
        wallpaper.width = None
        wallpaper.height = None
        wallpaper.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_wallpaper_height_wallpaper_width_and_more'),
    ]

    operations = [
        migrations.RunPython(
            set_wallpaper_width_height,
            delete_wallpaper_width_height
        )
    ]
