# Generated by Django 5.2 on 2025-05-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_set_wallpaper_width_height_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='height',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='width',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
