# Generated by Django 5.2 on 2025-06-01 07:02

from typing import cast
from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.conf import settings


def set_groups_and_permission(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name=settings.VERIFIED_GROUP_NAME)
    Group.objects.create(name=settings.CATEGORY_EDITOR_GROUP_NAME)
    Group.objects.create(name=settings.WALLPAPER_EDITOR_GROUP_NAME)


def delete_groups_and_permission(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Group = apps.get_model('auth', 'Group')
    Group.objects.all().delete()

    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_wallpaper_description_alter_category_slug_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(
            set_groups_and_permission,
            delete_groups_and_permission
        )
    ]
