# Generated by Django 5.2 on 2025-06-02 11:11

import common.image_utils
import common.unique_file_path_generators
import common.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_set_group_and_permission_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='compressed',
            field=models.ImageField(blank=True, editable=False, max_length=256, upload_to=common.unique_file_path_generators.UniqueFilePathGenerator(pathlib.PurePosixPath('wallpapers/compressed'), 'image'), validators=[common.validators.MaxFileSizeValidator(1048576), common.validators.ImageFormatAndFileExtensionsValidator((common.image_utils.ImageFormat['WEBP'],)), common.validators.ImageDimensionValidator(min_height=1024, min_width=1024)]),
        ),
    ]
