# Generated by Django 5.2 on 2025-06-02 13:57

import common.image_utils
import common.unique_file_path_generators
import common.validators
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_set_compressed_wallpaper_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(editable=False, height_field='height', max_length=256, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/soham/Projects/Wallpaperz/private')), unique=True, upload_to=common.unique_file_path_generators.UniqueFilePathGenerator(pathlib.PurePosixPath('wallpapers'), 'image'), validators=[common.validators.MaxFileSizeValidator(7340032), common.validators.ImageFormatAndFileExtensionsValidator((common.image_utils.ImageFormat['JPEG'],)), common.validators.ImageDimensionValidator(min_height=1024, min_width=1024)], width_field='width'),
        ),
    ]
