# Generated by Django 5.2 on 2025-06-02 14:03

from operator import attrgetter
import os
from pathlib import Path
from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from project import settings
from django.core.files.images import ImageFile
import shutil


wallpapers_directory: Path = settings.BASE_DIR / 'images/wallpapers/'


def set_wallpaper_images(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Wallpaper = apps.get_model('app', 'Wallpaper')

    files = sorted(wallpapers_directory.glob('*.jpg'), key=attrgetter('name'))
    
    for wallpaper, file in zip(Wallpaper.objects.all(), files):
        old_file = os.path.join(settings.MEDIA_ROOT, wallpaper.image.name)
        wallpaper.image.save(file.name, ImageFile(file.open('rb')))
        Path(old_file).unlink(missing_ok=True)


def restore_wallpaper_images(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Wallpaper = apps.get_model('app', 'Wallpaper')

    files = sorted(wallpapers_directory.glob('*.jpg'), key=attrgetter('name'))

    for wallpaper in Wallpaper.objects.all():
        old_file = os.path.join(settings.BASE_DIR / 'private', wallpaper.image.name)
        os.makedirs(settings.MEDIA_ROOT / 'wallpapers', exist_ok=True)
        shutil.move(str(old_file), settings.MEDIA_ROOT / 'wallpapers')




class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_wallpaper_image'),
    ]

    operations = [
        migrations.RunPython(
            set_wallpaper_images,
            restore_wallpaper_images
        )
    ]
