# Generated by Django 5.2 on 2025-06-05 07:02

from pathlib import Path
from typing import cast
from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.core.files.storage import storages, default_storage, FileSystemStorage
import shutil


def move_wallpapers_from_public_to_private_storage(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Wallpaper = apps.get_model('app', 'Wallpaper')
    wallpapers_base_path: Path = Wallpaper._meta.get_field('image').upload_to.base_path
    public_storage = cast(FileSystemStorage, default_storage)
    private_storage = cast(FileSystemStorage, storages['private'])
    shutil.move(
        Path(str(public_storage.location)) / wallpapers_base_path,
        Path(str(private_storage.location)) / wallpapers_base_path
    )


def move_wallpapers_from_private_to_public_storage(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Wallpaper = apps.get_model('app', 'Wallpaper')
    wallpapers_base_path: Path = Wallpaper._meta.get_field('image').upload_to.base_path
    public_storage = cast(FileSystemStorage, default_storage)
    private_storage = cast(FileSystemStorage, storages['private'])
    shutil.move(
        Path(str(private_storage.location)) / wallpapers_base_path,
        Path(str(public_storage.location)) / wallpapers_base_path
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_wallpaper_image'),
    ]

    operations = [
        migrations.RunPython(
            move_wallpapers_from_public_to_private_storage,
            move_wallpapers_from_private_to_public_storage
        )
    ]
